apiVersion: apps/v1
kind: Deployment
metadata:
  name: trips
spec:
  selector:
    matchLabels:
      app: trips
  replicas: 1
  template:
    metadata:
      labels:
        app: trips
    spec:
      containers:
      - name: trips
        image: registryehf3159.azurecr.io/tripinsights/trips:1.0
        env:
        - name: SQL_USER
          valueFrom:
            secretKeyRef:
              name: sqlusersecret
              key: sqluserkey
        - name: SQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sqlpasswordsecret
              key: sqlpasswordkey
        - name: SQL_SERVER
          valueFrom:
            secretKeyRef:
              name: sqlserversecret
              key: sqlserverkey
        - name: SQL_DBNAME
          valueFrom:
            secretKeyRef:
              name: sqldbnamesecret
              key: sqldbnamekey
        ports:
        - containerPort: 80
          name: redis
        volumeMounts:
            - name: secrets-store-inline
              mountPath: "/mnt/secrets-store"
              readOnly: true
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "azure-kvname"
            nodePublishSecretRef:                       # Only required when using service principal mode
              name: secrets-store-creds  
---
apiVersion: v1
kind: Service
metadata:
  name: trips
spec:
  ports:
  - port: 80
  selector:
    app: trips