apiVersion: apps/v1
kind: Deployment
metadata:
  name: userprofile
  namespace: api-namespace
spec:
  selector:
    matchLabels:
      app: userprofile
  replicas: 1
  template:
    metadata:
      labels:
        app: userprofile
    spec:
      containers:
      - name: userprofile
        image: registryehf3159.azurecr.io/tripinsights/userprofile:1.0
        env:
        - name: SQL_USER
          valueFrom:
            secretKeyRef:
              name: tisecrets
              key: sqluser
        - name: SQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: tisecrets
              key: sqlpassword
        - name: SQL_SERVER
          valueFrom:
            secretKeyRef:
              name: tisecrets
              key: sqlserver
        - name: SQL_DBNAME
          valueFrom:
            secretKeyRef:
              name: tisecrets
              key: sqldbname
        - name: ASPNETCORE_ENVIRONMENT
          valueFrom:
            secretKeyRef:
              name: tisecrets
              key: aspnetcore_environment
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: userprofile
spec:
  ports:
  - port: 80
  selector:
    app: userprofile
