apiVersion: apps/v1
kind: Deployment
metadata:
  name: userprofile
spec:
  selector:
    matchLabels:
      app: userprofile
  replicas: 1
  template:
    metadata:
      labels:
        app: userprofile
    spec:
      containers:
      - name: userprofile
        image: registryehf3159.azurecr.io/tripinsights/userprofile:1.0
        env:
        - name: SQL_USER
          valueFrom:
            secretKeyRef:
              name: sqlusersecret
              key: sqluserkey
        - name: SQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sqlpasswordsecret
              key: sqlpasswordkey
        - name: SQL_SERVER
          valueFrom:
            secretKeyRef:
              name: sqlserversecret
              key: sqlserverkey
        - name: SQL_DBNAME
          valueFrom:
            secretKeyRef:
              name: sqldbnamesecret
              key: sqldbnamekey
        ports:
        - containerPort: 80
        volumeMounts:
          - name: secrets-store-inline
            mountPath: "/mnt/secrets-store"
            readOnly: true
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "azure-kvname"
            nodePublishSecretRef:                       # Only required when using service principal mode
              name: secrets-store-creds                 # Only required when using service principal mode
  
---
apiVersion: v1
kind: Service
metadata:
  name: userprofile
spec:
  ports:
  - port: 80
  selector:
    app: userprofile